name: Create Archive
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Archive Release 1
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig install.sh README*'
    - name: Archive Release 2  
      uses: thedoctor0/zip-release@release.zip
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig install.sh README*'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: "true"
