name: create release
env:
#  TYPE: 'zip'
#  FILENAME: 'install_assets.zip'
#  FILENAME_DEPLOY: 'trac_util_scripts.zip'
#  EXCLUSIONS: '*.git* /*node_modules/* .editorconfig install.sh README*'
#  INCLUSIONS: 'trac_util_scripts.zip README* install.sh'
#  METADATA: ${{ github. }}
  TYPE: 'zip'
  FILENAME: '${{ github.event.repository.name }}_${{ github.event.release.tag_name }}.zip'
  FILENAME_DEPLOY: 'install_assets.zip'
  EXCLUSIONS: '*.git* /*node_modules/* .editorconfig install.sh README*'
  INCLUSIONS: 'install_assets.zip README* install.sh'
  BRANCH: '${{ github.event.release.target_commitish }}'
#  This next variable is a hack to see ALL of the DOM of the github variable to help you work out what bits you may need to extract (so even though it is commented out, don't delete!)
  #GITHUB_CONTEXT: ${{ toJson(github) }}
  GITHUB_CONTEXT: ${{ toJson(github.ref) }}

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Archive Release 1
      uses:  PVS-Australia/zip-release@main
      with:
        type: ${{ env.TYPE }}
        filename: ${{ env.FILENAME }}
        filename_deploy: ${{ env.FILENAME_DEPLOY }}
        exclusions: ${{ env.EXCLUSIONS }}
        #inclusions: 'trac_util_scripts.zip README* install.sh' 
        inclusions: ${{ env.INCLUSIONS }}
        github_context: ${{ env.GITHUB_CONTEXT }}
    - name: Upload Release
      uses: PVS-Australia/release-action@v1
      with:
        artifacts: ${{ env.FILENAME }}
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: "true"
