name: create release
env:
  TYPE: 'zip'
  FILENAME: 'install_assets.zip'
  FILENAME_DEPLOY: 'trac_util_scripts.zip'
  EXCLUSIONS: '*.git* /*node_modules/* .editorconfig install.sh README*'
  INCLUSIONS: 'trac_util_scripts.zip README* install.sh'
  METADATA: ${{ REPOSITORY_HOMEPAGE_URL }}

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Archive Release 1
      uses:  PVS-Australia/zip-release@main
      with:
        type: ${{ env.TYPE }}
        filename: ${{ env.FILENAME }}
        filename_deploy: ${{ env.FILENAME_DEPLOY }}
        exclusions: ${{ env.EXCLUSIONS }}
        #inclusions: 'trac_util_scripts.zip README* install.sh' 
        inclusions: ${{ env.INCLUSIONS }}
    - name: Upload Release
      uses: PVS-Australia/release-action@v1
      with:
        artifacts: ${{ env.FILENAME }}
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: "true"
